version: '3.8'

services:
  web:
    build: .
    container_name: django-football-web
    command: gunicorn football_project.wsgi:application --bind 0.0.0.0:8000 --workers=3 --timeout=120
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  static_volume:
  media_volume:
